#!/bin/bash
export PROJECTS='/home/mehmet/'
export RAHIB="$PROJECTS/RAHIB/RAHIB/"
export RAHIB_STORAGE="$RAHIB/STORAGE/"

pgrep -x sxhkd > /dev/null || sxhkd -c $RAHIB/CONFIGS/sys/sxhkdrc/sxhkdrc_8gb &

intern=eDP-1
extern=HDMI-1

if xrandr | grep "$extern disconnected"; then
    bspc monitor -d I II III IV V VI VII VIII IX X
else
    bspc monitor eDP-1 -d I II III IV V VI VII
    bspc monitor HDMI-1 -d VIII IX X
fi

bspc config border_width         0.5
bspc config window_gap          5
bspc config -m top_padding      40
bspc config ignore_ewmh_focus true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 60
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 50

#bspc config automatic_scheme spiral

############################################################################################
##################################### RULES ################################################
############################################################################################
bspc rule -a Terminator desktop='^1' follow=off
bspc rule -a xterm desktop='^1' follow=off

bspc rule -a Signal desktop='^4' follow=off
bspc rule -a Chromium desktop='^2' follow=off

bspc rule -a calibre desktop='^9' follow=off
bspc rule -a firefox-esr desktop='^3' follow=off
bspc rule -a openshot desktop='^6' follow=off

bspc rule -a Termite desktop='^2' follow=off
bspc rule -a UXTerm desktop='^2' follow=off

bspc rule -a Navigator desktop='^3' follow=off

bspc rule -a libreoffice desktop='^4' follow=off
bspc rule -a libreoffice-startcenter desktop='^4' follow=off
bspc rule -a burp-StartBurp desktop='^4' follow=off

bspc rule -a Transmission-gtk desktop='^5' follow=off

bspc rule -a vlc desktop='^7' follow=off
bspc rule -a VirtualBoxVM desktop='^7' follow=off
bspc rule -a Code desktop='^7' follow=off
bspc rule -a code desktop='^7' follow=off

bspc rule -a GLava state=floating layer=below sticky=true locked=true

bspc rule -a Onboard state=floating layer=above sticky=true
bspc rule -a display state=floating layer=above sticky=true
bspc rule -a Display state=floating layer=above sticky=true

wmname LG3D &

bspc rule -a android-studio state=floating border=off follow=on

############################################################################################
############################################################################################

bspc config normal_border_color "#000000"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

###############################################################################
########### KILLING STUFF SO AS TO NOT MESS UP GRAPHICS OR SLOW COMPUTER DOWN #
###############################################################################
pkill polybar
compton &
dunst &

WAL=~/wallpapers/$(ls ~/wallpapers | shuf -n 1)
/home/mehmet/miniconda3/envs/idris/bin/wal -i $WAL
expressions=("colorblocks")

RANDOM=$$$(date +%s)

selectedexpression=${expressions[ $RANDOM % ${#expressions[@]} ]}

bash ~/.config/polybar/$selectedexpression/scripts/pywal.sh $WAL

/home/mehmet/miniconda3/envs/idris/bin/pywalfox update

bash ~/.config/polybar/launch.sh --$selectedexpression &

xsetroot -cursor_name left_ptr
# xidlehook --not-when-fullscreen --not-when-audio --timer normal 100 'bash ~/.config/bspwm/slideshow' '' &
##################################
####### EXTRA STUFF ##############
##################################
#redshift &
##################################
#################################
#pkill stayfree-desktop
#/usr/bin/stayfree-desktop &
bash /home/mehmet/Proyectos/TANZIMAT/programstarter.bash /home/mehmet/Proyectos/TANZIMAT/programs.txt
/home/mehmet/miniconda3/envs/idris/bin/python /home/mehmet/Proyectos/TANZIMAT/scripts/youtube_watchlist.py &
